### PR TITLE
CIS Security Compliance Updates

### PR DESCRIPTION
**Pull request by jrlew-sg**
## CIS Security Compliance Updates

> Cloudtrail S3 bucket block public access and SSE configuration, SNS Topic encryption, add more outputs 

## Type of change
- [ ] Bug fix (fixes an issue)
- [x] New feature (adds functionality)

## Related issues

> Fix [#1]() 

### Development

- [x] Lint rules pass locally
- [x] Application changes have been tested thoroughly
- [ ] Automated tests covering modified code pass

### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### Code review 

- [ ] Pull request has a descriptive title and context useful to a reviewer. Screenshots or screencasts are attached as necessary
- [ ] "Ready for review" label attached and reviewers assigned
- [ ] Changes have been reviewed by at least one other contributor
- [ ] Pull request linked to task tracker where applicable

### CODE REVIEW

**Review by StratusChris — COMMENTED** [review]
@jrlew-sg - I think these all make sense. Is this a breaking change, or does it require any manual intervention, when applied to an existing configuration in our customer accounts?

**Comment by jrlew-sg** [comment]
@StratusChris This is a non-breaking change and has applied cleanly to several of our accounts so far.

**Comment by wesleykirklandsg** [comment]
@jrlew-sg I messaged you in Slack, but I'll gladly approve assuming your comments are still stated as true.

**Comment by chrischildresssg** [comment]
@jrlew-sg it looks like this PR is older, and has some conflicts.  We're going to need to apply a change to this module soon, but do you think this PR is easy enough to fix up for merge?

**Comment by jrlew-sg** [comment]
Closing for now as changes are unused. Can be revived later if still desired.

**Pull request closed without merging**
